version: "3"

volumes:
  postgres_data:
  mysql_data:

services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: davical
      POSTGRES_PASSWORD: davical

  davical:
    build:
      context: ./davical
    volumes:
      - ./:/var/www/html/
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/,
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - davical
